pollution_issues = [
    "Lead Poisoning",
    "Fracking Fluids",
    "Oil Spills",
    "Nitrate Pollution",
    "Plastic Microbeads",
    "Chlorine Byproducts",
    "Arsenic Contamination",
    "Radioactive Waste",
    "Mercury Bioaccumulation",
    "Phosphate Runoff",
    "Endocrine Disruptors",
    "Acid Mine Drainage",
    "Cyanobacterial Blooms",
    "E. coli Outbreaks",
    "Dioxin Contamination",
    "Salinization",
    "PCB Pollution",
    "Groundwater Depletion",
    "Petroleum Hydrocarbons",
    "Antibiotic Resistance",
    "Nutrient Overload",
    "Sediment Pollution",
    "PFAS Chemicals",
    "Viral Pathogens",
    "Organic Solvents",
    "Livestock Effluents",
    "Stormwater Runoff",
    "Desalination Brine",
    "Fluoride Excess",
    "Cryptosporidium Outbreaks",
    "Benzene Leaks",
    "Microplastic Pollution",
    "Legionella Growth",
    "Chromium Pollution",
    "Nanoparticle Contamination",
    "Asbestos Fibers",
    "Cyanide Spills",
    "Methane Seepage",
    "Radium Leaching",
    "Chloramine Byproducts",
    "Giardia Infections",
    "Atrazine Runoff",
    "Bisphenol A (BPA)",
    "Cadmium Poisoning",
    "Ash Pond Leakage",
    "Haloacetic Acids",
    "Salmonella Outbreaks",
    "Manganese Excess"
]
